arduino:
  baudrate: 115200
  arduino_serial_ports:
    Motor: "/dev/ttyACM1"
    US: "/dev/ttyUSB1"
    Lidar: "/dev/ttyACM0"

gpio:
  start_button_pin: 4
  team_button_pin: 26
  bumper_pins: [0, 1, 5, 6]

frequency: 10  # Rate 
queue_size: 1
map_boundaries: [0, 0, 3, 2]  # in m
resolution: 100  # for cm
radius: 40 # radius around obstacles
# sensor_positions: [
#                    [0, -12.5, 0, 4.712388],
#                    [-8, 10, 0, 2.3561294],
#                    [8.5, -12.5, 0, 4.712388],
#                    [-8, -10, 0, 3.92699],
#                    [8.5, 12.5, 0, 1.570796],
#                    [0, 12.5, 0, 1.570796],
#                    [-10, 5, 0, 3.141592],
#                    [-10, -5, 0, 3.141592],
#                    [8, 5, 0, 0],
#                    [8, -5, 0, 0]]

sensor_positions: [
                   [-0.10, 0.5, 0, 3.141592],
                   [-0.10, -0.5, 0, 3.141592]]

objectives: # Objectives are defined for each team.
  blue:
    plant:
      sequence0: [[2.8, .2, 0, 1]]
      sequence1: [[2.8, .2, 0, 1]]
    solar_panel:
      sequence0: [[2.275, 1.6, 1.57, -1],
                  [2.5, 1.6, 1.57, -1],
                  [2.725, 1.6, 1.57, -1],
                  [1.275, 1.6, 1.57, -1],
                  [1.5, 1.6, 1.57, -1],
                  [1.725, 1.6, 1.57, -1]]
    home:
      sequence0: [[2.8, 1.8, 0, 0], [2.8, .4, 4.71, 1], [2.8, 1.8, 0, 0]]
    debug:
      sequence0: [[2.25, 0.5, 0, 1], [2.25, 1.5, 0, 1], [0.75, 1.5, 0, 1], [0.75, 0.5, 0, 1], [1.5, 1, 0, 1]]

  yellow: # Multiple phases to complete in the given order.
    plant: # Multiple possibilities. If a path is not found for a sequence, the next closest sequence is chosen
      sequence0: [[2.55, 0.85, 3.49, 2, 1], [0.82, 0.2, 3.14, 0, 1], [0.4, 0.2, 3.14, 0, 1]]
    solar_panel:
      sequence0: [[0.275, 1.6, 1.57, -1],
                  [0.5, 1.6, 1.57, -1],
                  [0.725, 1.6, 1.57, -1],
                  [1.275, 1.6, 1.57, -1],
                  [1.5, 1.6, 1.57, -1],
                  [1.725, 1.6, 1.57, -1]]
    solar_panel_alt: [[0.2, 1.8, 0, -1]]
    home:
      sequence0: [[.2, 1.8, 0, 0], [.2, .4, 0, 1], [.2, 1.8, 0, 0]]
    debug:
      sequence0: [[2.25, 0.5, 0, 1], [2.25, 1.5, 0, 1], [0.75, 1.5, 0, 1], [0.75, 0.5, 0, 1], [1.5, 1, 0, 1]]
  
phases: # robot has the declared below game elapsed time to complete each sequence
  plant:
    sequence0: 20
    sequence1: 40
  solar_panel: 70
  solar_panel_alt: 70
  home: 80
  debug:
    sequence0: 100
