arduino:
  baudrate: 115200
  arduino_serial_ports:
    Motor: "/dev/ttyACM1"
    US: "/dev/ttyUSB1"
    Lidar: "/dev/ttyACM0"

gpio:
  start_button_pin: 4
  team_button_pin: 26
  bumper_pins: [0, 1, 5, 6]

frequency: 10  # Rate 
queue_size: 1
map_boundaries: [0, 0, 2, 3]  # in m
resolution: 100  # for cm
sensor_positions: [
                   [0, -12.5, 0, 4.712388],
                   [-8, 10, 0, 2.3561294],
                   [8.5, -12.5, 0, 4.712388],
                   [-8, -10, 0, 3.92699],
                   [8.5, 12.5, 0, 1.570796],
                   [0, 12.5, 0, 1.570796],
                   [-10, 5, 0, 3.141592],
                   [-10, -5, 0, 3.141592],
                   [8, 5, 0, 0],
                   [8, -5, 0, 0]]

# An objective is a list of waypoints with (x, y, theta) coordinates
objectives: [[1.5, 1.0, 0], [0.75, 0.50, 0], [1.15, 1.50, 0], [1.50, 1.00, 0], [0.50, 0.50, 0]]
