arduino:
  baudrate: 115200
  known_sensors: [Motor, US]


gpio:
  start_button_pin: 4
  emergency_button_pin: 26
  bumper_pins: [0, 1, 5, 6]

frequency: 10   # Rate 
queue_size: 10 
map_boundaries: [0, 0, 200, 300]  # in cm
sensor_positions: [(x, y, z, angle), ...] # TODO
